<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LQQA004" name="TestMethods" tests="25" failures="6" timestamp="7 Mar 2016 02:01:29 GMT" time="1508.774" errors="0">
  <testcase name="loginSuccess" time="6.687" classname="com.blemall.smokeTest.testcases.TestCase_01_Login"/>
  <testcase name="wrongPasswordAlert" time="3.392" classname="com.blemall.smokeTest.testcases.TestCase_01_Login"/>
  <testcase name="usernameNotExist" time="3.876" classname="com.blemall.smokeTest.testcases.TestCase_01_Login"/>
  <testcase name="A1_addToCartFromSearch" time="28.036" classname="com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart"/>
  <testcase name="A2_addToShopCart" time="19.125" classname="com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart"/>
  <testcase name="A3_oneGoodsEditAddNum" time="24.399" classname="com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart.goodsEditAddNum(TestCase_03_ShoppingCart.java:581)
	at com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart.A3_oneGoodsEditAddNum(TestCase_03_ShoppingCart.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- A3_oneGoodsEditAddNum -->
  <testcase name="A4_oneGoodsEditDeleteNum" time="24.001" classname="com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart"/>
  <testcase name="A5_addGoodNumCheckStock" time="15.248" classname="com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart"/>
  <testcase name="A6_oneGoodToSubmit" time="16.46" classname="com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart"/>
  <testcase name="A7_oneGoodsEditDelete" time="24.09" classname="com.blemall.smokeTest.testcases.TestCase_03_ShoppingCart"/>
  <testcase name="addAddress" time="31.873" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder"/>
  <testcase name="sendTimeChooseCheck" time="18.863" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder"/>
  <testcase name="selfTakeCheck" time="83.795" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.checkSelfTake(TestCase_04_CreateOrder.java:359)
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.selfTakeCheck(TestCase_04_CreateOrder.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- selfTakeCheck -->
  <testcase name="selfTakeFeeCheck" time="21.264" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder">
    <failure type="java.lang.IllegalMonitorStateException">
      <![CDATA[java.lang.IllegalMonitorStateException
	at java.lang.Object.wait(Native Method)
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.checkSelfTakeFee(TestCase_04_CreateOrder.java:653)
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.selfTakeFeeCheck(TestCase_04_CreateOrder.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- selfTakeFeeCheck -->
  <testcase name="payNow" time="24.209" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder"/>
  <testcase name="companyInvoiceCheck" time="76.598" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.gotoShoppingCart(TestCase_04_CreateOrder.java:477)
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.companyInvoiceCheck(TestCase_04_CreateOrder.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- companyInvoiceCheck -->
  <testcase name="goodsSaleMoneyCheck" time="17.607" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder"/>
  <testcase name="goodsSaleNumCheck" time="81.885" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.checkgoodsSaleNum(TestCase_04_CreateOrder.java:253)
	at com.blemall.smokeTest.testcases.TestCase_04_CreateOrder.goodsSaleNumCheck(TestCase_04_CreateOrder.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- goodsSaleNumCheck -->
  <testcase name="totalAmountCheck" time="18.303" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder"/>
  <testcase name="orderAmountDetailsCheck" time="20.428" classname="com.blemall.smokeTest.testcases.TestCase_04_CreateOrder"/>
  <testcase name="freshGoodsDeliveryFee" time="21.442" classname="com.blemall.smokeTest.testcases.TestCase_05_ChargeFee"/>
  <testcase name="normalGoodsScenario1" time="20.986" classname="com.blemall.smokeTest.testcases.TestCase_05_ChargeFee"/>
  <testcase name="normalGoodsScenario2" time="19.505" classname="com.blemall.smokeTest.testcases.TestCase_05_ChargeFee">
    <failure type="java.lang.AssertionError" message="小于48元重量大于5kg常温商品-自营 测试场景不通过">
      <![CDATA[java.lang.AssertionError: 小于48元重量大于5kg常温商品-自营 测试场景不通过
	at org.testng.Assert.fail(Assert.java:94)
	at com.blemall.smokeTest.testcases.TestCase_05_ChargeFee.checkFee(TestCase_05_ChargeFee.java:319)
	at com.blemall.smokeTest.testcases.TestCase_05_ChargeFee.normalGoodsScenario2(TestCase_05_ChargeFee.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- normalGoodsScenario2 -->
  <testcase name="normalGoodsScenario3" time="18.228" classname="com.blemall.smokeTest.testcases.TestCase_05_ChargeFee"/>
  <testcase name="freshGoodsNoDeliveryFee" time="19.29" classname="com.blemall.smokeTest.testcases.TestCase_05_ChargeFee"/>
</testsuite> <!-- TestMethods -->
